/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ExtraDecoder */

#ifndef _Included_org_example_ExtraDecoder
#define _Included_org_example_ExtraDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_ExtraDecoder
 * Method:    decode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_example_ExtraDecoder_decode
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
